"\\dataserv\Installers\Deployed\PDQ\TeamViewer\TeamViewer_Host_Setup.exe" /S

"C:\Program Files (x86)\TeamViewer\TeamViewer.exe" assignment --id 0001CoABChAM7UQA3hwR7YxII1ESUwtfEigIACAAAgAJAHQ6gwWWBGgZkPflZM-135qp3Zl60ddpMbZBzelx5YbnGkDg-C8OqX_1gDJfQiVagtmcXNWgJnwkWQ3bzk5vYWLkZloPWnp0IfXwUMI1kAl0hULseQCgSz3QOdWs_u53o_1fIAEQ-eGiigs=

"C:\Program Files\TeamViewer\TeamViewer.exe" assignment --id 0001CoABChAM7UQA3hwR7YxII1ESUwtfEigIACAAAgAJAHQ6gwWWBGgZkPflZM-135qp3Zl60ddpMbZBzelx5YbnGkDg-C8OqX_1gDJfQiVagtmcXNWgJnwkWQ3bzk5vYWLkZloPWnp0IfXwUMI1kAl0hULseQCgSz3QOdWs_u53o_1fIAEQ-eGiigs=